import Head from "next/head";
import { Inter } from "@next/font/google";
import HomeBanner from "@/Components/Home/HomeBanner";
import HomeCard from "@/Components/Home/HomeCard";
import FeatureOne from "@/Components/Home/FeatureOne";
import FeatureTwo from "@/Components/Home/FeatureTwo";
import FeatureThree from "@/Components/Home/FeatureThree";
import HomeReview from "@/Components/Home/HomeReview";
import HomeFaq from "@/Components/Home/HomeFaq";
import BgLight from "../../public/images/exclusiveWebHosting.svg";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div style={{backgroundImage:`url(${<BgLight />})`, height:'100%', width:'100%'}} className={`bg-center bg-contain bg-repeat bg-[url(${(<BgLight width="1100px" height="700px" />)})]`}>
          <HomeBanner />
        </div>

        <div className="max-w-screen-2xl mx-auto px-5">
          <HomeCard />
          <FeatureOne />
          <FeatureTwo />
          <FeatureThree />
          <HomeReview />
          <HomeFaq />
        </div>
      </main>
    </>
  );
}
