import Head from "next/head";
import { Inter } from "@next/font/google";
import Header from "@/Components/Header/Header";
import HomeBanner from "@/Components/Home/HomeBanner";
import HomeCard from "@/Components/Home/HomeCard";
import FeatureOne from "@/Components/Home/FeatureOne";
import FeatureTwo from "@/Components/Home/FeatureTwo";
import FeatureThree from "@/Components/Home/FeatureThree";
import HomeReview from "@/Components/Home/HomeReview";
import HomeFaq from "@/Components/Home/HomeFaq";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const mainBannerClass = `bg-center bg-contain bg-repeat bg-[url('../../public/images/homeBannerBgSurface.svg')]`
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <div className={mainBannerClass}>
          <HomeBanner />
        </div>

        <div className="max-w-screen-2xl mx-auto px-5">
        <HomeCard />
        <FeatureOne />
        <FeatureTwo />
        <FeatureThree />
        <HomeReview />
        <HomeFaq />
        </div>
      </main>
    </>
  );
}
