import Head from "next/head";
import { Inter } from "@next/font/google";
import HomeBanner from "@/Components/Home/HomeBanner";
import HomeCard from "@/Components/Home/HomeCard";
import ArticleSection from "@/Components/Home/ArticleSection";
import WebsiteUpSection from "@/Components/Home/WebsiteUpSection";
import SiteRacksParkSection from "@/Components/Home/SiteRacksParkSection";
import HomeReview from "@/Components/Home/HomeReview";
import HomeFaq from "@/Components/Home/HomeFaq";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* {{backgroundImage:`url('../../public/images/Sandipan_das.jgeg')`, backgroundSize:'cover', backgroundPosition:'center center'}} */}
        {/* // it's using on css. and css by defult catch public folder path. */}
        <div style={{backgroundImage:`url('/images/homeBannerBgSurface.svg')`, backgroundSize:'contain', backgroundAttachment:'fixed', backgroundPosition:'top center'}}>
          <HomeBanner />
        </div>

        <div className="max-w-screen-2xl mx-auto px-5">
          <HomeCard />
          <ArticleSection />
          <WebsiteUpSection />
          <SiteRacksParkSection />
          <HomeReview />
          <HomeFaq />
        </div>
      </main>
    </>
  );
}
